replicaCount: 2

image:
  repository: 688436101433.dkr.ecr.us-east-1.amazonaws.com/eks-gitops-app
  tag: "545954d2baeb8a7f19e77e6d4050cfa3f560decb"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: ""

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: "eks-gitops-app-sa"
  annotations: {}
